
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://estonoesunacharla.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /

# Google tracking id

google-tracking-id: "UA-116422939-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "es"
author: "EstoNoEsUnaCharla"
title: "{ #EstoNoEsUnaCharla }"
description: "Conversaciones sobre ciencia y tecnología, una vez al mes."
keywords: "dissemination, science, technology, celera"
favicon: "/img/favicon.ico"

#################
# Header layout #
#################

black-favicon: "/img/header.png"
#background-img: "../img/backgrounds/eneuc.png"


######################
# Latest post layout #
######################

latest-post-background-img: "../img/latest-post-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 12
back-speed: 1
start-delay: 1000
delete-delay: 3500
lines: # You can add HTML Tags in the Text
  - text: "Los temas más interesantes sobre ciencia y tecnología, cada mes."
  - text: "Lo que siempre quisiste saber sobre Física Cuántica."
  - text: "¿Alguna vez te preguntaste cómo llegamos a la Luna?"
  - text: "Aprende sobre edición de genes con CRISPR."
  - text: "Pregunta hasta saciar tu curiosidad."
  - text: "Descubre una nueva rama de la ciencia cada mes."
  - text: "Nunca antes las matemáticas fueron tan interesantes."
  - text: "Una comunidad de gente con inquietudes."
  - text: "Un espacio divertido donde aprender y dialogar."
  - text: "Lo que nunca te atreviste a preguntar sobre Inteligencia Artificial."
  - text: "Un club de gente que podría llevar monóculo (si quisiera)."
  - text: "Nunca dejes de aprender."
  - text: "Ciencia, sin rollos."
  - text: "¿Y qué pasaría si...?"
  - text: "¿Sabes cómo funciona un ordenador cuántico?"
  - text: "Temas interesantes, explorados en profundidad."
  - text: "Mucho más que meras charlas de divulgación."
  - text: "¿Qué es lo que sabemos sobre la consciencia humana?"
  - text: "¿Quieres saber más sobre ciberseguridad?"
  - text: "Grafeno, mucho grafeno. Montones de grafeno."
  - text: "Cómo funciona nuestro cerebro."
  - text: "¿Cómo se detectan los exoplanetas habitables?."
  - text: "La frontera de la Física, la Informática, y la Biología."
  - text: "Explorando juntos el futuro de la Ciencia y la Tecnología."
  - text: "Grandes personas (y buena cerveza)."
  - text: "Pregúntame cualquier cosa."
  - text: "Los últimos avances en ingeniería."
  - text: "Las mejores ideas para terraformar Marte."

me-img: "/img/eneuc/logo-fondo-azul-cuadrado.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#d2e6e7"
apple-status-bar-style: "black-translucent"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False

post-preview-words: 96

paginate: 10

email-share: True
fb-share: True
twitter-share: True
linkedin-share: False
reddit-share: False
google-plus-share: False

tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

# disqus-shortname: "" # "estonoesunacharla"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/events-square/cyberethics.jpg"
    date: "24 octubre 2018"
    description: "Cuando tu coche automático sabe más que tú: ciber-ética, con Sara Lumbreras y Javier Garmón."
  - image: "/img/events-square/cyberethics.jpg"
    date: "24 octubre 2018"
    description: "Cuando tu coche automático sabe más que tú: ciber-ética, con Sara Lumbreras y Javier Garmón."

# Uncomment this to add a last circle to the timeline, without words
timeline-img: "/img/eneuc.png"

###########
# Contact #
###########

email: "estonoesunacharla@acelerame.org"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: false
author_blurb_image: ""

##################
# Social Buttons #
##################

social:
  - title: "envelope"
    url: "mailto:estonoesunacharla@acelerame.org"
  - title: "twitter"
    url: "https://twitter.com/NoEsUnaCharla"
  - title: "instagram"
    url: "https://www.instagram.com/estonoesunacharla"

##################
# GPG on Keybase #
##################

# keybase-username: johnsmith
# keybase-in-social: True
# keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  ¿Qué?: 'about'
  ¿Dónde?: 'latest-post'
  ¿Cuándo?: 'timeline'
  ¿Quiénes?: 'team'
  Contacto: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
